Increment 7
OmAsana/yapraktikum pull request #6
Opened 2022-01-21 13:45 UTC by OmAsana

2022-01-21 14:39 UTC, OmAsana commented
Думаю, что логика флаша на диск у меня немного топроно сделана. 
Можно было лечшу, точно.

Но я здесь уже спешил, так как потратил пару дней на 2 других варианта, которые не вошли в этот пр.

2022-01-23 16:10 UTC, Bazys requested changes
есть небольшие комментарии, но в целом ок!

2022-01-23 16:10 UTC, Bazys commented on cmd/server/main.go
> +		defer handler.FlushToDisk()
вот тут происходит сохранение на диск.
А зачем теперь нужен WaitGroup?
только для гарантии записи?

2022-01-23 16:10 UTC, Bazys commented on internal/agent/agent.go
> +	var sendRequest = func(metricStream <-chan handlers.Metrics) {
какой глубокий смысл в этом?

2022-01-23 16:10 UTC, Bazys commented on internal/agent/config.go
> +type Config struct {
может здесь сделать немонго более объектноориентированно?
один конструктор и все остальное функции структуры?

2022-01-23 16:10 UTC, Bazys commented on internal/agent/cmdArgs.go
> +package agent
зачем это?

2022-01-23 16:10 UTC, Bazys commented on internal/server/server.go
> +type ServerOpts func(server *MetricsServer)
в агенте ты это вынес в отдельный файл и там код лучше читается.

2022-01-23 16:10 UTC, Bazys commented on internal/server/server.go
> +func (ms MetricsServer) FlushToDisk() {
а смысл?

2022-01-23 16:10 UTC, Bazys commented on internal/server/server.go
> +func validateCounter(value string) (int64, error) {
вроде же вынес вспомогатеьные функции в pkg

2022-01-24 16:52 UTC, OmAsana commented on cmd/server/main.go
> +		defer handler.FlushToDisk()
В main есть wg.Wait(), который ждет, когда сервер завершится при Shutdown

2022-01-24 16:54 UTC, OmAsana commented on internal/agent/agent.go
> +	var sendRequest = func(metricStream <-chan handlers.Metrics) {
Думаю великого смысле сздесь нет. Было желание в этом месте на каналах сделать. 

Можно сделать и без канала, так как в этом месте параллелнссти нет )

2022-01-24 17:44 UTC, OmAsana commented on internal/agent/config.go
> +type Config struct {
Переписал на ООП. 
На получается протестировать деволный конфиг, так как в command.Parse лезут флаги тестов. 
Приходится отдельно тестировать метод с флагами.

2022-01-24 17:56 UTC, merged